### ISSUE TITLE
Bug: Article dates don't show on all blog posts

### ISSUE THREAD

**Issue by Ngoakor12** [YajanaRao/yajanarao.github.io#32]
It looks like every post except has a date except for "[API documentation using Swagger](https://yajanarao.github.io/technical/2021-10-1-api-specs/)" and "[Setting up Touchpad Gestures in your Ubuntu Laptop](https://yajanarao.github.io/technical/2021-12-02-gestures-in-linux/)". See image:
![image](https://user-images.githubusercontent.com/54069197/196037025-8ad5df04-7eec-4747-b1b9-975afe357f6c.png)

Dates are pretty important to see the relevency of certain material I think so I thought I should raise it.

**Comment by YajanaRao** [comment]
Yes, Makes sense
